### ISSUE TITLE
该引擎能否简化移植到单片机上呢？

### ISSUE THREAD

**Issue by ColdHuo** [play175/Hello2D#1]
设想将该引擎移植到处理能力较弱的单片机上，驱动分辨率较低的屏幕，例如单色的128x64或者rgb的240x320，如果能够移植的话需要做那些工作呢，求大神解答。
ps:我的本意是想实现一款类似arduboy的小掌机，硬件部分难度不大，但是在游戏生态上还要做很多工作，例如简单的引擎啥的。

**Comment by play175** [comment]
你好，引擎是跨平台的，纯C实现，理论上可以在所有平台运行，包括嵌入式系统
